name: Rust Clippy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "cargo-build"

    - name: Run rust-clippy
      run:
        cargo clippy
        --all-targets
        --all-features
